name: ci 

on:
  push:
    branches:
      - master 
jobs:
  steps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Dependencies
      - run: |
          pip install sphinx sphinx-rtd-theme myst_parser sphinx_design
      - name: Sphinx build
      - run: |
          sphinx-build source build
      - name: Deploy
        uses: peaceiris/actions-gh-pahes@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/
          force_orphan: true